// Generated by ranger-starter. Do not edit: change ranger.project.json.
pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "helloworld"
include(":app")
