#!/usr/bin/env node
// android-gradle -- run a Gradle task through the project wrapper.
//
// Generated by ranger-starter. Do not edit: change ranger.project.json and
// run `npm run setup -- --apply`.
//
// WHY THIS EXISTS. Android Studio never installs a `gradle` command. It uses
// the Gradle wrapper inside the project. A generated `android:build` that
// ran `gradle assembleDebug` therefore failed on a machine that already
// builds Android apps. This script is the wrapper: it fetches
// gradle-wrapper.jar if the file is missing (`write_file` cannot emit a
// binary), then runs GradleWrapperMain the way `./gradlew` does.
//
//   node scripts/android-gradle.js assembleDebug
//   node scripts/android-gradle.js installDebug
//
// SPDX-License-Identifier: MIT
'use strict';
const fs = require('fs');
const path = require('path');
const https = require('https');
const { spawnSync } = require('child_process');

const ROOT = path.join(__dirname, '..', 'platforms', 'android');
const WRAPPER_DIR = path.join(ROOT, 'gradle', 'wrapper');
const JAR = path.join(WRAPPER_DIR, 'gradle-wrapper.jar');
// Official wrapper JAR from the Gradle 8.9 tag. The properties file pins the
// distribution; this JAR only bootstraps the download.
const JAR_URL = 'https://github.com/gradle/gradle/raw/v8.9.0/gradle/wrapper/gradle-wrapper.jar';

function fail(msg) {
  console.error('android-gradle: ' + msg);
  process.exit(1);
}

function javaName() {
  return process.platform === 'win32' ? 'java.exe' : 'java';
}

function javaFromHome(home) {
  if (!home) return '';
  const bin = path.join(home, 'bin', javaName());
  return fs.existsSync(bin) ? bin : '';
}

function studioHomes() {
  const homes = [];
  const dirs = [];
  if (process.platform === 'darwin') {
    dirs.push('/Applications');
    if (process.env.HOME) dirs.push(path.join(process.env.HOME, 'Applications'));
  } else if (process.platform === 'win32') {
    if (process.env['ProgramFiles']) dirs.push(process.env['ProgramFiles']);
    if (process.env['ProgramFiles(x86)']) dirs.push(process.env['ProgramFiles(x86)']);
  } else {
    dirs.push('/opt');
    if (process.env.HOME) dirs.push(process.env.HOME);
  }
  for (let i = 0; i < dirs.length; i++) {
    let names = [];
    try { names = fs.readdirSync(dirs[i]); } catch (e) { continue; }
    for (let j = 0; j < names.length; j++) {
      const n = names[j];
      if (n.indexOf('Android Studio') !== 0 && n !== 'android-studio') continue;
      homes.push(path.join(dirs[i], n));
    }
  }
  return homes;
}

function findJava() {
  const fromEnv = javaFromHome(process.env.JAVA_HOME);
  if (fromEnv) return fromEnv;
  const homes = studioHomes();
  for (let i = 0; i < homes.length; i++) {
    const candidates = [
      path.join(homes[i], 'Contents', 'jbr', 'Contents', 'Home'),
      path.join(homes[i], 'Contents', 'jbr'),
      path.join(homes[i], 'jbr')
    ];
    for (let j = 0; j < candidates.length; j++) {
      const bin = javaFromHome(candidates[j]);
      if (bin) return bin;
    }
  }
  return 'java';
}

function findStudioGradle() {
  const binName = process.platform === 'win32' ? 'gradle.bat' : 'gradle';
  const homes = studioHomes();
  for (let i = 0; i < homes.length; i++) {
    const gradleRoots = [
      path.join(homes[i], 'Contents', 'gradle'),
      path.join(homes[i], 'gradle')
    ];
    for (let j = 0; j < gradleRoots.length; j++) {
      let names = [];
      try { names = fs.readdirSync(gradleRoots[j]); } catch (e) { continue; }
      names.sort();
      for (let k = 0; k < names.length; k++) {
        const candidate = path.join(gradleRoots[j], names[k], 'bin', binName);
        if (fs.existsSync(candidate)) return candidate;
      }
    }
  }
  return '';
}

function fetchJar(url, dest, hops, done) {
  if (hops > 5) {
    done(new Error('too many redirects'));
    return;
  }
  const req = https.get(url, { headers: { 'User-Agent': 'ranger-starter' } }, (res) => {
    if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
      res.resume();
      fetchJar(res.headers.location, dest, hops + 1, done);
      return;
    }
    if (res.statusCode !== 200) {
      res.resume();
      done(new Error('HTTP ' + res.statusCode));
      return;
    }
    const out = fs.createWriteStream(dest);
    res.pipe(out);
    out.on('finish', () => out.close(() => done(null)));
    out.on('error', done);
  });
  req.on('error', done);
}

function runWrapper(args) {
  const java = findJava();
  const result = spawnSync(
    java,
    ['-Dorg.gradle.appname=gradlew', '-classpath', JAR, 'org.gradle.wrapper.GradleWrapperMain'].concat(args),
    { cwd: ROOT, stdio: 'inherit' }
  );
  if (result.error && result.error.code === 'ENOENT') {
    fail('no JDK. Set JAVA_HOME, or open platforms/android in Android Studio.');
  }
  process.exit(result.status === null ? 1 : result.status);
}

function runBinary(bin, args) {
  const result = spawnSync(bin, args, { cwd: ROOT, stdio: 'inherit' });
  process.exit(result.status === null ? 1 : result.status);
}

function fallback(args, why) {
  console.error('android-gradle: ' + why);
  const studio = findStudioGradle();
  if (studio) {
    console.error('android-gradle: using Android Studio Gradle instead');
    runBinary(studio, args);
  }
  const onPath = spawnSync('gradle', ['--version'], { encoding: 'utf8' });
  if (onPath.status === 0) {
    console.error('android-gradle: using gradle on PATH instead');
    runBinary('gradle', args);
  }
  fail('could not run Gradle. Open platforms/android in Android Studio, or install a JDK 17+ and retry.');
}

const args = process.argv.slice(2);
if (args.length === 0) fail('usage: node scripts/android-gradle.js <task>...');
if (!fs.existsSync(ROOT)) fail('no Android host at platforms/android. Run apply first.');

if (fs.existsSync(JAR) && fs.statSync(JAR).size > 0) {
  runWrapper(args);
}

fs.mkdirSync(WRAPPER_DIR, { recursive: true });
console.error('android-gradle: fetching gradle-wrapper.jar');
fetchJar(JAR_URL, JAR, 0, (err) => {
  if (err) {
    try { fs.unlinkSync(JAR); } catch (e) {}
    fallback(args, 'could not fetch the Gradle wrapper (' + err.message + ')');
    return;
  }
  runWrapper(args);
});
