#!/usr/bin/env node
// rgr -- compile a Ranger program and run it, and FAIL when the compile fails.
//
// Generated by ranger-starter. Do not edit: change ranger.project.json and
// run `npm run setup -- --apply`.
//
// WHY THIS EXISTS. Ranger compilers through 3.5.1 print `Compilation FAILED`
// and exit 0. Written the obvious way,
//
//     npx rgrc src/Main.rgr -o=Main.js && node build/Main.js
//
// the `&&` is satisfied by that zero, the PREVIOUS build is still on disk, and
// node runs that one -- so the edit looks applied and the test looks green when
// neither is true. Later compilers exit non-zero, and which one is installed
// here is whatever `npm install` resolved. So, on either: the output is deleted
// first, the log is read as well as the status, and a missing output is an error.
//
//   node scripts/rgr.js run   <src.rgr> [args...]   compile to JavaScript and run
//   node scripts/rgr.js build <src.rgr> [-l=<lang>] compile only
//   node scripts/rgr.js check <src.rgr>             compile and report
//
// Anything after `--` goes to the compiler.
//
// SPDX-License-Identifier: MIT
'use strict';
const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');

// Generated from the compiler's own target list.
const EXT = {
  es6: 'js',
  go: 'go',
  scala: 'scala',
  java7: 'java',
  swift3: 'swift',
  swift6: 'swift',
  kotlin: 'kt',
  dart: 'dart',
  cpp: 'cpp',
  php: 'php',
  csharp: 'cs',
  python: 'py',
  rust: 'rs',
  llvm: 'll',
};

function usage(code) {
  console.error('usage: node scripts/rgr.js run|build|check <src.rgr> [-l=<lang>] [-d=<dir>] [-- compiler flags]');
  process.exit(code);
}

const argv = process.argv.slice(2);
const cmd = argv.shift();
if (['run', 'build', 'check'].indexOf(cmd) < 0) usage(1);
const src = argv.shift();
if (!src) usage(1);
if (!fs.existsSync(src)) { console.error('rgr: no such file: ' + src); process.exit(1); }

let lang = 'es6';
let outdir = 'build';
const args = [];
let passthru = [];
while (argv.length) {
  const a = argv.shift();
  if (a === '--') { passthru = argv.slice(); break; }
  if (a.startsWith('-l=')) { lang = a.slice(3); continue; }
  if (a.startsWith('-d=')) { outdir = a.slice(3); continue; }
  args.push(a);
}

const ext = EXT[lang];
if (!ext) { console.error('rgr: unknown language ' + lang); process.exit(1); }
const base = path.basename(src, '.rgr');
const outFile = base + '.' + ext;
const out = path.join(outdir, outFile);
fs.mkdirSync(outdir, { recursive: true });
fs.rmSync(out, { force: true });

// The compiler is resolved from node_modules, so there is no npx process, no
// .cmd shim to find on Windows, and no chance of reaching the network.
let rgrc;
try {
  rgrc = require.resolve('ranger-compiler/dist/rgrc.js');
} catch (e) {
  console.error('rgr: ranger-compiler is not installed. Run `npm install`.');
  process.exit(1);
}

const compile = spawnSync(
  process.execPath,
  [rgrc, src, '-l=' + lang, '-d=' + outdir, '-o=' + outFile].concat(passthru),
  { encoding: 'utf8' }
);
const log = (compile.stdout || '') + (compile.stderr || '');

// Three independent failure signals, because no single one is reliable across
// compiler versions: the exit status, the word FAILED in the log, and a missing
// output file.
const failed =
  compile.status !== 0 ||
  log.indexOf('Compilation FAILED') >= 0 ||
  log.indexOf('[FAIL]') >= 0 ||
  !fs.existsSync(out);

if (failed) {
  process.stderr.write(log);
  console.error('rgr: ' + src + ' did not compile');
  process.exit(1);
}

if (cmd === 'check') { console.log('rgr: ' + src + ' compiles (' + lang + ')'); process.exit(0); }
if (cmd === 'build') { console.log('rgr: ' + out); process.exit(0); }

const RUNNERS = { es6: [process.execPath, []], python: ['python3', []], go: ['go', ['run']] };
const runner = RUNNERS[lang];
if (!runner) {
  console.error('rgr: cannot run ' + lang + ' here; the output is ' + out);
  process.exit(1);
}
const run = spawnSync(runner[0], runner[1].concat([out], args), { stdio: 'inherit' });
process.exit(run.status === null ? 1 : run.status);
